default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: broom123*
  host: db-broom
  pool: 5

development:
  <<: *default
  database: broom_app_development

test:
  <<: *default
  database: broom_app_test

production:
  <<: *default
  database: broom_app_production
  username: broom_app
  password: <%= ENV["BROOM_APP_DATABASE_PASSWORD"] %>
